import { Role } from "@prisma/client";
import { NextResponse } from "next/server";
import { timetableUpdateSchema } from "@/lib/academic-validation";
import { authorizeApi } from "@/lib/api-authorization";
import { prisma } from "@/lib/prisma";

type Context={params:Promise<{id:string}>};
export async function PATCH(request:Request,{params}:Context){const access=await authorizeApi([Role.ADMIN]);if(access.response)return access.response;const parsed=timetableUpdateSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Invalid timetable entry"},{status:400});const id=(await params).id,existing=await prisma.timetableEntry.findUnique({where:{id}});if(!existing)return NextResponse.json({error:"Timetable entry not found"},{status:404});const conflict=await prisma.timetableEntry.findFirst({where:{id:{not:id},weekday:parsed.data.weekday,startsAt:{lt:parsed.data.endsAt},endsAt:{gt:parsed.data.startsAt},OR:[{teacherId:existing.teacherId},{room:{equals:parsed.data.room,mode:"insensitive"}}]}});if(conflict)return NextResponse.json({error:"The teacher or room already has an overlapping class"},{status:409});const entry=await prisma.$transaction(async(tx)=>{const updated=await tx.timetableEntry.update({where:{id},data:parsed.data});await tx.auditEvent.create({data:{actorId:access.user!.id,action:"timetable.updated",entityType:"TimetableEntry",entityId:id,metadata:{weekday:updated.weekday,startsAt:updated.startsAt,endsAt:updated.endsAt,room:updated.room}}});return updated;});return NextResponse.json({entry});}
export async function DELETE(_:Request,{params}:Context){const access=await authorizeApi([Role.ADMIN]);if(access.response)return access.response;const id=(await params).id,entry=await prisma.timetableEntry.findUnique({where:{id},include:{_count:{select:{attendance:true}}}});if(!entry)return NextResponse.json({error:"Timetable entry not found"},{status:404});if(entry._count.attendance)return NextResponse.json({error:"This class has attendance history and cannot be deleted"},{status:409});await prisma.$transaction([prisma.timetableEntry.delete({where:{id}}),prisma.auditEvent.create({data:{actorId:access.user!.id,action:"timetable.deleted",entityType:"TimetableEntry",entityId:id}})]);return NextResponse.json({deleted:true});}
