import { Role } from "@prisma/client";
import { NextResponse } from "next/server";
import { timetableInputSchema } from "@/lib/academic-validation";
import { timetableScope } from "@/lib/academic-scope";
import { authorizeApi } from "@/lib/api-authorization";
import { prisma } from "@/lib/prisma";

export async function GET(){const access=await authorizeApi([Role.ADMIN,Role.TEACHER,Role.STUDENT,Role.GUARDIAN]);if(access.response)return access.response;const entries=await prisma.timetableEntry.findMany({where:timetableScope(access.user!.role,access.user!.id),include:{course:true,teacher:{include:{user:true}}},orderBy:[{weekday:"asc"},{startsAt:"asc"}]});return NextResponse.json({entries});}
export async function POST(request:Request){const access=await authorizeApi([Role.ADMIN]);if(access.response)return access.response;const parsed=timetableInputSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Invalid timetable entry"},{status:400});const assignment=await prisma.courseTeacher.findUnique({where:{courseId_teacherId:{courseId:parsed.data.courseId,teacherId:parsed.data.teacherId}},include:{course:true,teacher:true}});if(!assignment||!assignment.course.isActive)return NextResponse.json({error:"Select an active teacher-course assignment"},{status:400});const conflict=await prisma.timetableEntry.findFirst({where:{weekday:parsed.data.weekday,startsAt:{lt:parsed.data.endsAt},endsAt:{gt:parsed.data.startsAt},OR:[{teacherId:parsed.data.teacherId},{room:{equals:parsed.data.room,mode:"insensitive"}}]}});if(conflict)return NextResponse.json({error:"The teacher or room already has an overlapping class"},{status:409});const entry=await prisma.$transaction(async(tx)=>{const created=await tx.timetableEntry.create({data:parsed.data});await tx.auditEvent.create({data:{actorId:access.user!.id,action:"timetable.created",entityType:"TimetableEntry",entityId:created.id,metadata:{courseId:created.courseId,teacherId:created.teacherId,weekday:created.weekday}}});return created;});return NextResponse.json({entry},{status:201});}
