import { Prisma, Role } from "@prisma/client";
import { requireUser } from "@/lib/authorization";
import { prisma } from "@/lib/prisma";
import { AcademicYearForm } from "@/components/academic-year-form";
import { EnrollmentForm } from "@/components/enrollment-form";
import { EnrollmentEditor } from "@/components/enrollment-editor";

function scope(role:Role,userId:string):Prisma.EnrollmentWhereInput{if(role===Role.ADMIN)return{};if(role===Role.TEACHER)return{course:{teachers:{some:{teacher:{userId}}}}};if(role===Role.STUDENT)return{student:{userId}};return{student:{guardians:{some:{guardian:{userId}}}}};}
export default async function EnrollmentsPage(){const user=await requireUser([Role.ADMIN,Role.TEACHER,Role.STUDENT,Role.GUARDIAN]);const [enrollments,students,courses,academicYears]=await Promise.all([prisma.enrollment.findMany({where:scope(user.role,user.id),include:{student:{include:{user:true}},course:true,academicYear:true},orderBy:{enrolledAt:"desc"}}),user.role===Role.ADMIN?prisma.student.findMany({where:{user:{status:"ACTIVE"}},include:{user:true},orderBy:{admissionNumber:"asc"}}):Promise.resolve([]),user.role===Role.ADMIN?prisma.course.findMany({where:{isActive:true},orderBy:{code:"asc"}}):Promise.resolve([]),prisma.academicYear.findMany({orderBy:{startsAt:"desc"}})]);
return <main><header><div><p className="eyebrow">ACADEMIC PLACEMENT</p><h1>Enrollments</h1><p>{user.role===Role.ADMIN?"Place students into courses for a defined academic year.":"View course placements available to your account."}</p></div></header>{user.role===Role.ADMIN&&<><section className="panel managementPanel"><div className="panelHead"><div><p className="eyebrow">ACADEMIC CALENDAR</p><h2>Create academic year</h2></div></div><AcademicYearForm/></section><section className="panel managementPanel"><div className="panelHead"><div><p className="eyebrow">NEW PLACEMENT</p><h2>Enroll a student</h2></div></div>{students.length&&courses.length&&academicYears.length?<EnrollmentForm students={students.map((item)=>({id:item.id,label:`${item.admissionNumber} — ${item.user.firstName} ${item.user.lastName}`}))} courses={courses.map((item)=>({id:item.id,label:`${item.code} — ${item.name}`}))} academicYears={academicYears.map((item)=>({id:item.id,label:item.name,isCurrent:item.isCurrent}))}/>:<p>Create an academic year and ensure active student and course records exist before enrolling.</p>}</section></>}<section className="panel tablePanel"><div className="panelHead"><div><h2>Enrollment register</h2><p>{enrollments.length} placement{enrollments.length===1?"":"s"}</p></div></div>{enrollments.length===0?<div className="emptyState"><h2>No enrollments yet</h2><p>Enrollment records visible to this account will appear here.</p></div>:<div className="tableWrap"><table><thead><tr><th>Student</th><th>Course</th><th>Academic year</th><th>Level</th><th>Status</th>{user.role===Role.ADMIN&&<th>Actions</th>}</tr></thead><tbody>{enrollments.map((item)=><tr key={item.id}><td><strong>{item.student.admissionNumber}</strong><small>{item.student.user.firstName} {item.student.user.lastName}</small></td><td><strong>{item.course.code}</strong><small>{item.course.name}</small></td><td>{item.academicYear.name}</td><td>{item.yearLevel}</td><td><span className={`status status${item.status}`}>{item.status.toLowerCase()}</span></td>{user.role===Role.ADMIN&&<td><EnrollmentEditor id={item.id} yearLevel={item.yearLevel} status={item.status}/></td>}</tr>)}</tbody></table></div>}</section></main>;}
